name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'docs/**'

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
    - name: Create build tag
      run: |
        export BUILD_TAG=build-$(date -u +'%Y%m%d%H%M')
        echo -n $BUILD_TAG > tag
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tag
        path: tag

  build-windows:
    runs-on: windows-latest
    needs: Init
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release, Debug]
    steps:
    - uses: actions/checkout@v4
    - name: Install vcpkg
      shell: pwsh
      run: |
        git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
        & "$env:VCPKG_ROOT\bootstrap-vcpkg.bat" -disableMetrics
    - name: CMake generate
      run: >
        cmake -S . -B build -A x64
        -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
        -DVCPKG_TARGET_TRIPLET=x64-windows
        -DXISO_BUILD_TESTS=ON
    - name: Build
      run: cmake --build build --config ${{ matrix.configuration }} -j $env:NUMBER_OF_PROCESSORS
    - name: Test
      working-directory: build
      run: ctest -C ${{ matrix.configuration }} --output-on-failure
    - name: Prepare artifacts
      run: |
        mkdir artifacts
        mv -vb build\main\${{ matrix.configuration }}\extract-xiso.exe, LICENSE.TXT artifacts
        cd artifacts
        powershell Compress-Archive . ../extract-xiso-Win64_${{ matrix.configuration }}.zip
    - uses: actions/upload-artifact@v4
      with:
        name: extract-xiso_Win64_${{ matrix.configuration }}
        path: extract-xiso-Win64_${{ matrix.configuration }}.zip

  build-linux:
    runs-on: ubuntu-latest
    needs: Init
    steps:
    - uses: actions/checkout@v4
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
        $VCPKG_ROOT/bootstrap-vcpkg.sh -disableMetrics
    - name: CMake generate
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DXISO_BUILD_TESTS=ON
    - name: Build
      run: cmake --build build -j $(nproc --all)
    - name: Test
      working-directory: build
      run: ctest --output-on-failure
    - name: Prepare artifacts
      run: |
        mkdir artifacts
        mv -v build/main/extract-xiso LICENSE.TXT artifacts
        cd artifacts
        zip -r ../extract-xiso_${{ runner.os }}.zip *
    - uses: actions/upload-artifact@v4
      with:
        name: extract-xiso_${{ runner.os }}
        path: extract-xiso_${{ runner.os }}.zip

  build-macos:
    runs-on: macos-latest
    needs: Init
    steps:
    - uses: actions/checkout@v4
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git $VCPKG_ROOT
        $VCPKG_ROOT/bootstrap-vcpkg.sh -disableMetrics
    - name: CMake generate
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DXISO_BUILD_TESTS=ON
    - name: Build
      run: cmake --build build -j $(sysctl -n hw.ncpu)
    - name: Test
      working-directory: build
      run: ctest --output-on-failure
    - name: Prepare artifacts
      run: |
        mkdir artifacts
        mv -v build/main/extract-xiso LICENSE.TXT artifacts
        cd artifacts
        zip -r ../extract-xiso_${{ runner.os }}.zip *
    - uses: actions/upload-artifact@v4
      with:
        name: extract-xiso_${{ runner.os }}
        path: extract-xiso_${{ runner.os }}.zip

  Release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
    - name: Get package info
      run: |
        echo "BUILD_TAG=$(cat dist/tag/tag)" >> $GITHUB_ENV
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.BUILD_TAG }}
        name: ${{ env.BUILD_TAG }}
        prerelease: false
        draft: false
        files: dist/*/*.zip
